remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Modern Java
description: Modern Development with Java
show_downloads: false
github:
  another_url: https://github.com/manojsuthar123
